# Dataset de estimativa de vendas de marca de carro
O dataset abaixo é um conjunto de dados mensais por veículo da BMW, que inclui estimativas de receita, participação no segmento e dados macroeconômicos.

In [ ]:
# Começar importando bibliotecas básicas do Python (nem todas serão usadas) e outra necessária para o google colab
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#-------------------------------
from google.colab import files

In [ ]:
# Fazer upload do dataset
uploaded = files.upload()

Saving bmw_global_sales_2018_2025.csv to bmw_global_sales_2018_2025.csv

In [ ]:
# Transformar o CSV em dataframe
df = pd.read_csv('bmw_global_sales_2018_2025.csv')

In [ ]:
# Explorando o dataset: tipos de dados por coluna
df.dtypes

Year                  int64
Month                 int64
Region               object
Model                object
Units_Sold            int64
Avg_Price_EUR         int64
Revenue_EUR           int64
BEV_Share           float64
Premium_Share       float64
GDP_Growth          float64
Fuel_Price_Index    float64
dtype: object

In [ ]:
# Explorando o dataset: Informações básicas sobre as colunas

df.describe()

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000

In [ ]:
# Explorando o dataset: primeiras informações
df.head()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.5,1.0
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.5,1.0

## Análise exploratória

In [ ]:
#Quantas unidades foram vendidas por ano?
df.groupby('Year')['Units_Sold'].sum()

Year
2018    2765193
2019    2759838
2020    3036556
2021    3036564
2022    3083306
2023    3177788
2024    3293423
2025    3362777
Name: Units_Sold, dtype: int64

In [ ]:

df.groupby(['Year','Region'])['Revenue_EUR'].sum()

Year  Region
2018  China          43906098288
      Europe         45228201998
      RestOfWorld    44656431893
      USA            42984486220
2019  China          45538083738
      Europe         40930362440
      RestOfWorld    45128605357
      USA            44955377150
2020  China          48298566836
      Europe         49914479893
      RestOfWorld    50468166213
      USA            46956854938
2021  China          51733254067
      Europe         47025481430
      RestOfWorld    48364466721
      USA            47169734186
2022  China          48894314065
      Europe         51195726384
      RestOfWorld    49045729011
      USA            47965554803
2023  China          52239601754
      Europe         48846616197
      RestOfWorld    51274297412
      USA            51222057360
2024  China          53989799850
      Europe         52413234209
      RestOfWorld    52395827640
      USA            52672206151
2025  China          57155301885
      Europe         53324850050
      RestOfWorld    49737510359
      USA            55388019620
Name: Revenue_EUR, dtype: int64

In [ ]:
df.groupby(['Year','Region'])['GDP_Growth'].mean()

Year  Region
2018  China          3.115833
      Europe         2.992500
      RestOfWorld    3.579167
      USA            3.099167
2019  China          2.686667
      Europe         3.767500
      RestOfWorld    2.835000
      USA            3.072500
2020  China          2.795833
      Europe         3.022500
      RestOfWorld    3.131667
      USA            3.084167
2021  China          3.403333
      Europe         2.745833
      RestOfWorld    2.573333
      USA            3.019167
2022  China          2.835000
      Europe         2.898333
      RestOfWorld    3.082500
      USA            3.442500
2023  China          2.662500
      Europe         3.215000
      RestOfWorld    2.952500
      USA            3.503333
2024  China          2.738333
      Europe         3.450000
      RestOfWorld    3.145000
      USA            3.319167
2025  China          2.789167
      Europe         3.305000
      RestOfWorld    3.075833
      USA            2.502500
Name: GDP_Growth, dtype: float64

In [ ]:
(((df[(df['Year'] == 2019) & (df['Region'] == 'China')]['Revenue_EUR'].sum())-(df[(df['Year'] == 2018) & (df['Region'] == 'China')]['Revenue_EUR'].sum()))/(df[(df['Year'] == 2018) & (df['Region'] == 'China')]['Revenue_EUR'].sum()))*100

np.float64(3.7169903809148965)

In [ ]:
(df['Revenue_EUR'] * df['BEV_Share']).groupby(df['Year']).sum()

Year
2018    3.584102e+09
2019    7.876576e+09
2020    1.377386e+10
2021    1.843216e+10
2022    2.364076e+10
2023    2.963630e+10
2024    3.607550e+10
2025    4.188767e+10
dtype: float64

In [ ]:
df.groupby(['Region', 'Model'])['Units_Sold'].sum().sort_values(ascending=False)

Region       Model
China        iX          856644
Europe       X7          820143
China        X5          816868
             5 Series    813129
Europe       i4          800865
China        X3          794213
USA          3 Series    792166
RestOfWorld  X7          784423
             i4          779974
USA          i4          779329
             X5          778952
RestOfWorld  3 Series    768488
China        i4          765519
RestOfWorld  iX          763772
             X3          763639
China        X7          763185
RestOfWorld  MINI        762095
USA          X3          758971
Europe       iX          758710
USA          iX          757786
             5 Series    750405
RestOfWorld  5 Series    746266
             X5          745215
USA          X7          744323
Europe       X5          744099
             5 Series    742724
USA          MINI        737715
China        MINI        735790
Europe       MINI        735605
             3 Series    733992
China        3 Series    711402
Europe       X3          709038
Name: Units_Sold, dtype: int64

In [ ]:
df.groupby(['Region', 'Model'])['Premium_Share'].mean()

Region       Model
China        3 Series    17.569479
             5 Series    17.569479
             MINI        17.569479
             X3          17.569479
             X5          17.569479
             X7          17.569479
             i4          17.569479
             iX          17.569479
Europe       3 Series    17.327708
             5 Series    17.327708
             MINI        17.327708
             X3          17.327708
             X5          17.327708
             X7          17.327708
             i4          17.327708
             iX          17.327708
RestOfWorld  3 Series     5.987500
             5 Series     5.987500
             MINI         5.987500
             X3           5.987500
             X5           5.987500
             X7           5.987500
             i4           5.987500
             iX           5.987500
USA          3 Series    17.756250
             5 Series    17.756250
             MINI        17.756250
             X3          17.756250
             X5          17.756250
             X7          17.756250
             i4          17.756250
             iX          17.756250
Name: Premium_Share, dtype: float64