# **Dataset de estudantes - Análise exploratória básica**
Esse notebook contém uma análise exploratória básica de um dataset sobre estudantes, que pode ser encontrado no Kaggle de nome e link a seguir:"Online Learning Student Dropout Dataset" https://www.kaggle.com/datasets/mohamedasak/online-learning-student-dropout-dataset

## Importações básicas

In [24]:
# Importação do files

from google.colab import files

In [25]:
# Upload do dataset

uploaded = files.upload()

Saving student_dropout_dataset.csv to student_dropout_dataset (1).csv

In [26]:
# Importação de bibliotecas básicas e padrão

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
# Transformação do CSV em dataframe

df = pd.read_csv('student_dropout_dataset.csv')

## Aspectos básicos do dataset

In [28]:
# Primeiras cinco linhas

df.head()

,student_id,age,region,enroll_date,exam_season,courses_enrolled,completed_assignments,completion_rate,login_frequency,last_activity_days_ago,forum_posts_count,dropout_score,label,label_multiclass,label_name
0,STU00001,26,Alexandria,2024-01-13,0,3,5,0.3571,5.29,10,5,0.1064,0,0,active
1,STU00002,23,Amman,2024-05-05,0,6,0,0.0000,0.84,7,0,0.6627,1,2,dropped
2,STU00003,17,Dubai,2024-03-12,0,3,1,0.0435,1.79,36,0,0.7299,1,2,dropped
3,STU00004,23,Alexandria,2024-12-12,0,6,13,0.4396,0.78,9,0,0.5315,1,1,at-risk
4,STU00005,20,Baghdad,2024-02-14,0,5,5,0.2078,0.92,11,0,0.7904,1,2,dropped

In [29]:
# Quantidade de linhas do df

len(df)

5000

In [30]:
# Quantidade de dados nulos por coluna

df.isnull().sum()

student_id                0
age                       0
region                    0
enroll_date               0
exam_season               0
courses_enrolled          0
completed_assignments     0
completion_rate           0
login_frequency           0
last_activity_days_ago    0
forum_posts_count         0
dropout_score             0
label                     0
label_multiclass          0
label_name                0
dtype: int64

In [31]:
# Tipos de dados por coluna

df.dtypes

student_id                 object
age                         int64
region                     object
enroll_date                object
exam_season                 int64
courses_enrolled            int64
completed_assignments       int64
completion_rate           float64
login_frequency           float64
last_activity_days_ago      int64
forum_posts_count           int64
dropout_score             float64
label                       int64
label_multiclass            int64
label_name                 object
dtype: object

In [32]:
# Linhas duplicadas

df.duplicated().sum()

np.int64(0)

## Análise básica do dataset

In [33]:
# Dados básicos da idade

df['age'].describe()

count    5000.000000
mean       23.736600
std         4.583211
min        17.000000
25%        20.000000
50%        24.000000
75%        27.000000
max        40.000000
Name: age, dtype: float64

In [34]:
# Quantidade de estudante por idade

df['age'].value_counts().sort_index()

age
17    591
18    227
19    233
20    303
21    352
22    368
23    412
24    400
25    375
26    334
27    315
28    304
29    230
30    181
31    107
32     98
33     60
34     44
35     24
36     16
37     16
38      5
39      4
40      1
Name: count, dtype: int64

In [35]:
# Quantidade de estudante por região

df['region'].value_counts()

region
Doha          534
Baghdad       532
Riyadh        510
Casablanca    509
Tunis         499
Alexandria    493
Cairo         484
Dubai         482
Amman         481
Beirut        476
Name: count, dtype: int64

In [36]:
# Dados básicos de frequência

df['login_frequency'].describe()

count    5000.000000
mean        3.453820
std         3.248316
min         0.100000
25%         0.980000
50%         2.440000
75%         4.942500
max        14.000000
Name: login_frequency, dtype: float64

In [37]:
# Dados básicos das últimas atividades

df['last_activity_days_ago'].describe()

count    5000.0000
mean        9.3564
std         9.4361
min         1.0000
25%         2.0000
50%         6.0000
75%        13.0000
max        70.0000
Name: last_activity_days_ago, dtype: float64

In [38]:
# Dados básicos da taxa de conclusão

df['completion_rate'].describe()

count    5000.000000
mean        0.260985
std         0.249010
min         0.000000
25%         0.053900
50%         0.206700
75%         0.389025
max         1.000000
Name: completion_rate, dtype: float64

In [39]:
# Informações básicas de evasão

df['dropout_score'].describe()

count    5000.000000
mean        0.431556
std         0.263529
min         0.000000
25%         0.204575
50%         0.441550
75%         0.658325
max         1.000000
Name: dropout_score, dtype: float64

In [40]:
# Comparação de dados de alunos por classificação de risco de evasão

df.groupby('label_name').mean(numeric_only=True)

,age,exam_season,courses_enrolled,completed_assignments,completion_rate,login_frequency,last_activity_days_ago,forum_posts_count,dropout_score,label,label_multiclass
label_name,,,,,,,,,,,
active,23.856808,0.059272,3.993545,10.214789,0.512990,6.668122,8.231808,7.980634,0.126825,0.0,0.0
at-risk,23.816597,0.088996,3.977150,3.484666,0.175312,2.706254,9.024053,3.257968,0.448672,1.0,1.0
dropped,23.529700,0.135334,4.028169,1.678506,0.085271,0.861066,10.868340,1.251684,0.732105,1.0,2.0