In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('ecommerce_user_behavior_8000.csv')

In [4]:
df.isnull().sum()

user_id               160
age                   160
gender                160
device_type           160
time_on_site          160
pages_viewed          160
previous_purchases    160
cart_items            160
discount_seen         160
ad_clicked            160
returning_user        160
avg_session_time      160
bounce_rate           160
purchase              160
dtype: int64

In [3]:
df.head()

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0

In [5]:
df[df.isnull().T.any()]

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
16,17.0,NaN,Male,Desktop,19.26,15.0,6.0,7.0,0.0,0.0,0.0,12.18,51.30,1.0
20,21.0,19.0,Male,Mobile,NaN,7.0,9.0,8.0,0.0,0.0,0.0,14.69,96.95,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7975,7976.0,43.0,Female,Mobile,9.14,2.0,3.0,5.0,0.0,0.0,0.0,6.68,NaN,1.0
7976,7977.0,26.0,Male,Mobile,18.55,12.0,12.0,NaN,0.0,1.0,1.0,27.73,23.00,1.0
7981,7982.0,39.0,Female,Mobile,22.47,9.0,9.0,5.0,0.0,0.0,NaN,14.65,0.27,1.0
7983,7984.0,47.0,Male,Mobile,NaN,7.0,10.0,7.0,1.0,1.0,0.0,4.00,83.26,1.0
7986,7987.0,28.0,Male,Desktop,NaN,15.0,10.0,9.0,0.0,1.0,0.0,4.34,60.37,1.0

In [6]:
df.dtypes

user_id               float64
age                   float64
gender                 object
device_type            object
time_on_site          float64
pages_viewed          float64
previous_purchases    float64
cart_items            float64
discount_seen         float64
ad_clicked            float64
returning_user        float64
avg_session_time      float64
bounce_rate           float64
purchase              float64
dtype: object

In [7]:
df.loc[df.age.isnull(),'age'] = 18.0
df.loc[df.gender.isnull(),'gender'] = 'Unidentified'
df.loc[df.device_type.isnull(),'device_type'] = 'anyone'
df.loc[df.time_on_site.isnull(),'time_on_site'] = 0.00
df.loc[df.pages_viewed.isnull(),'pages_viewed'] = 0.0
df.loc[df.previous_purchases.isnull(),'previous_purchases'] = 0.0
df.loc[df.cart_items.isnull(),'cart_items'] = 0.0
df.loc[df.discount_seen.isnull(),'discount_seen'] = 0.0
df.loc[df.ad_clicked.isnull(),'ad_clicked'] = 0.0
df.loc[df.returning_user.isnull(),'returning_user'] = 0.0
df.loc[df.avg_session_time.isnull(),'avg_session_time'] = 0.0
df.loc[df.bounce_rate.isnull(),'bounce_rate'] = 0.0
df.loc[df.purchase.isnull(),'purchase'] = 0.0

In [8]:
df.duplicated().sum()

np.int64(0)

In [25]:
df[df.age>18.0].describe()

,user_id,age,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
count,7506.000000,7665.000000,7665.000000,7665.000000,7665.000000,7665.000000,7665.000000,7665.000000,7665.000000,7665.000000,7665.000000,7665.000000
mean,4009.442846,39.066014,15.413872,9.756947,6.815134,4.443183,0.492498,0.492498,0.500978,15.512240,48.976817,0.978604
std,2308.994620,11.756492,8.555018,5.557234,4.350075,2.909148,0.499976,0.499976,0.500032,10.017702,29.708336,0.144710
min,1.000000,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2022.250000,29.000000,8.070000,5.000000,3.000000,2.000000,0.000000,0.000000,0.000000,7.430000,23.180000,1.000000
50%,4005.500000,39.000000,15.520000,10.000000,7.000000,4.000000,0.000000,0.000000,1.000000,14.050000,48.250000,1.000000
75%,6008.750000,49.000000,22.750000,15.000000,11.000000,7.000000,1.000000,1.000000,1.000000,22.220000,75.540000,1.000000
max,8000.000000,59.000000,30.000000,19.000000,14.000000,9.000000,1.000000,1.000000,1.000000,44.750000,99.970000,1.000000

In [26]:
df.purchase.unique()

array([1., 0.])